# Generated by Django 5.1.5 on 2025-03-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0003_alter_flashcard_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="is_answered",
        ),
    ]
