# Generated by Django 5.1.5 on 2025-04-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0004_remove_flashcard_is_answered"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"]},
        ),
    ]
