# Generated by Django 5.1.5 on 2025-11-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0005_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
